// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehh3QjCFg63yhsBTc-247cORArhgPkZE',
    appId: '1:934223700817:web:1d7bcf3ecaa4600d79a970',
    messagingSenderId: '934223700817',
    projectId: 'chit-chat-b680d',
    authDomain: 'chit-chat-b680d.firebaseapp.com',
    databaseURL: 'https://chit-chat-b680d-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-b680d.appspot.com',
    measurementId: 'G-H28JQ2NF0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApNhE4Mm4Y49WWepdXuyRNrK_vfmu7bUs',
    appId: '1:934223700817:android:fe55068d58c8ef0479a970',
    messagingSenderId: '934223700817',
    projectId: 'chit-chat-b680d',
    databaseURL: 'https://chit-chat-b680d-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-b680d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqtHdhdIC2lkUlD4WFJUU1Q-UMxLr1KXA',
    appId: '1:934223700817:ios:10603aaf0bcc75b079a970',
    messagingSenderId: '934223700817',
    projectId: 'chit-chat-b680d',
    databaseURL: 'https://chit-chat-b680d-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-b680d.appspot.com',
    iosBundleId: 'com.projectend.contectList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqtHdhdIC2lkUlD4WFJUU1Q-UMxLr1KXA',
    appId: '1:934223700817:ios:c19db09e7b3701b479a970',
    messagingSenderId: '934223700817',
    projectId: 'chit-chat-b680d',
    databaseURL: 'https://chit-chat-b680d-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-b680d.appspot.com',
    iosBundleId: 'com.projectend.contectList.RunnerTests',
  );
}
