// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZP8fWAtblw2RUii5w2JsPgguDY8QIUA',
    appId: '1:60414514188:web:f8a62aef41e5660de40a29',
    messagingSenderId: '60414514188',
    projectId: 'contact-60b30',
    authDomain: 'contact-60b30.firebaseapp.com',
    storageBucket: 'contact-60b30.appspot.com',
    measurementId: 'G-LXSQQ09D55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZgro928EfKo0CczWwYvnCcEDJYuwR8g',
    appId: '1:60414514188:android:603b2e1e018e898ce40a29',
    messagingSenderId: '60414514188',
    projectId: 'contact-60b30',
    storageBucket: 'contact-60b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMejsGi1q6uLtYaYj_yOTfew93o6Iitzo',
    appId: '1:60414514188:ios:73ce1163a2f02459e40a29',
    messagingSenderId: '60414514188',
    projectId: 'contact-60b30',
    storageBucket: 'contact-60b30.appspot.com',
    iosBundleId: 'com.projectend.contectList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMejsGi1q6uLtYaYj_yOTfew93o6Iitzo',
    appId: '1:60414514188:ios:501c6cbab789355ee40a29',
    messagingSenderId: '60414514188',
    projectId: 'contact-60b30',
    storageBucket: 'contact-60b30.appspot.com',
    iosBundleId: 'com.projectend.contectList.RunnerTests',
  );
}
